"""empty message

Revision ID: ba2bfd8b477c
Revises: f4d1bcc786e7
Create Date: 2024-03-11 07:05:08.451016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba2bfd8b477c'
down_revision = 'f4d1bcc786e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publisher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emblem', sa.String(length=16), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publisher', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.drop_column('emblem')

    # ### end Alembic commands ###
